repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0
    hooks:
    -   id: trailing-whitespace
    -   id: end-of-file-fixer
    -   id: check-yaml
    -   id: check-added-large-files

-   repo: https://github.com/pycqa/isort
    rev: 5.12.0
    hooks:
    -   id: isort
        args: [--profile=black, --line-length=100]

-   repo: https://github.com/psf/black
    rev: 23.3.0
    hooks:
    -   id: black
        args: [--line-length=100]

-   repo: https://github.com/pycqa/flake8
    rev: 6.0.0
    hooks:
    -   id: flake8
        args: [--max-line-length=100, --extend-ignore=E203,F541,W503]  # Ignore whitespace before ':', lazy string interpolation, and line breaks before binary operators
        exclude: F541

-   repo: https://github.com/pre-commit/mirrors-mypy
    rev: v1.3.0
    hooks:
    -   id: mypy
        additional_dependencies: [types-requests]
        args: [--ignore-missing-imports]

-   repo: local
    hooks:
    -   id: unittest-check
        name: unittest-check
        entry: python3 -m unittest discover tests
        language: system
        pass_filenames: false
        always_run: true
