services:
  fogis-api-client:
    build:
      context: .
      dockerfile: Dockerfile.dev
    container_name: fogis-api-client-dev
    networks:
      - fogis-network
    ports:
      - "8080:8080"
    volumes:
      - .:/app
      - ./data:/app/data
      - ./logs:/app/logs
      # Don't mount the venv directory to avoid conflicts
      - /app/.venv
    env_file:
      - .env.dev
    environment:
      - PYTHONUNBUFFERED=1
      - FLASK_ENV=development
      - FLASK_DEBUG=1
      - TZ=Europe/Stockholm
      # Ensure correct dependency versions
      - PIP_EXTRA_INDEX_URL=https://pypi.org/simple
    healthcheck:
      # Use a verbose health check for development to help diagnose issues
      # Use 0.0.0.0 instead of 127.0.0.1 to ensure it works in all network configurations
      test: [
        "CMD-SHELL",
        "curl -v http://0.0.0.0:8080/ > /tmp/health_check.log 2>&1 && \
         echo 'Health check response:' && \
         cat /tmp/health_check.log && \
         curl -s -o /dev/null -w '%{http_code}' http://0.0.0.0:8080/ | grep -q 200 || \
         (echo 'Health check failed:' && cat /tmp/health_check.log && exit 1)"
      ]
      interval: 15s
      timeout: 10s
      retries: 10
      start_period: 30s
    init: true
    restart: unless-stopped
    command: ["python", "fogis_api_gateway.py"]

  mock-fogis-server:
    build:
      context: .
      dockerfile: Dockerfile.mock
    container_name: mock-fogis-server
    networks:
      - fogis-network
    ports:
      - "5001:5001"
    volumes:
      - ./integration_tests:/app/integration_tests
    environment:
      - PYTHONUNBUFFERED=1
      - FLASK_ENV=development
      - FLASK_DEBUG=1
      - MOCK_SERVER_PORT=5001
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:5001/health"]
      interval: 10s
      timeout: 5s
      retries: 3
      start_period: 10s
    restart: unless-stopped

  integration-tests:
    build:
      context: .
      dockerfile: Dockerfile.test
    container_name: fogis-api-client-tests
    networks:
      - fogis-network
    volumes:
      - ./tests:/app/tests
      - ./integration_tests:/app/integration_tests
      - ./test-results:/app/test-results
    environment:
      - PYTHONUNBUFFERED=1
      - API_URL=http://fogis-api-client-dev:8080
      - MOCK_SERVER_URL=http://mock-fogis-server:5001
    depends_on:
      - fogis-api-client
      - mock-fogis-server
    # We're removing the health check dependency to allow tests to run even if the service is unhealthy
    # This way we can see which tests are failing and why
    command: ["pytest", "integration_tests", "-v"]

networks:
  fogis-network:
    external: true
    name: fogis-network
