version: '3.8'

services:
  fogis-api-client:
    build:
      context: .
      dockerfile: Dockerfile.dev
    container_name: fogis-api-client-dev
    networks:
      - fogis-network
    ports:
      - "8080:8080"
    environment:
      - PYTHONUNBUFFERED=1
    command: ["python", "fogis_api_gateway.py"]

  mock-fogis-server:
    build:
      context: .
      dockerfile: Dockerfile.mock
    container_name: mock-fogis-server
    networks:
      - fogis-network
    ports:
      - "5001:5001"
    environment:
      - PYTHONUNBUFFERED=1
      - MOCK_SERVER_PORT=5001

  integration-tests:
    build:
      context: .
      dockerfile: Dockerfile.test
    container_name: fogis-api-client-tests
    networks:
      - fogis-network
    environment:
      - PYTHONUNBUFFERED=1
      - API_URL=http://fogis-api-client-dev:8080
      - MOCK_SERVER_URL=http://mock-fogis-server:5001
    depends_on:
      - fogis-api-client
      - mock-fogis-server
    command: ["pytest", "integration_tests", "-v", "--log-cli-level=INFO"]

networks:
  fogis-network:
    driver: bridge
