version: '3.8'

# This file is automatically loaded when running docker-compose up
# It provides development-specific overrides

services:
  fogis-api-client:
    # Mount the source code for development
    volumes:
      - ./:/app
      - ./data:/app/data
      - ./logs:/app/logs
    environment:
      - FLASK_DEBUG=1
      - LOG_LEVEL=DEBUG
    # Use a different command for development to enable auto-reloading
    command: ["python", "-m", "flask", "run", "--host=0.0.0.0", "--port=8080", "--reload"]
    # Expose additional ports for debugging
    ports:
      - "8080:8080"
      - "5678:5678"  # For remote debugging if needed
    # Override healthcheck for development to be more lenient
    healthcheck:
      test: ["CMD-SHELL", "curl -s -o /dev/null -w '%{http_code}' http://localhost:8080/ | grep -q 200 || exit 1"]
      interval: 15s
      timeout: 10s
      retries: 5
      start_period: 30s
