version: '3.8'

services:
  fogis-api-client:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: fogis-api-client-service
    networks:
      - fogis-network
    ports:
      - "8080:8080"
    volumes:
      - ./data:/app/data
      - ./logs:/app/logs
    env_file:
      - .env
    environment:
      - PYTHONUNBUFFERED=1
      - TZ=Europe/Stockholm
      # Set default values for required environment variables
      # These will be overridden by .env file if it exists
      - FOGIS_USERNAME=${FOGIS_USERNAME:-demo_user}
      - FOGIS_PASSWORD=${FOGIS_PASSWORD:-demo_pass}
      - FLASK_DEBUG=${FLASK_DEBUG:-0}
      - LOG_LEVEL=${LOG_LEVEL:-INFO}
    healthcheck:
      # Simplified health check that works more reliably
      test: ["CMD", "curl", "-f", "http://localhost:8080/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 60s
    deploy:
      resources:
        limits:
          cpus: '0.50'
          memory: 512M
        reservations:
          cpus: '0.25'
          memory: 256M
    restart: unless-stopped
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"
    # Add stop grace period to control shutdown behavior
    stop_grace_period: 10s
    # Add init: true to handle signals properly
    init: true

networks:
  fogis-network:
    # Make the network configuration more flexible
    # If the network doesn't exist externally, it will be created locally
    external: ${USE_EXTERNAL_NETWORK:-false}
    name: fogis-network
    # Add driver configuration for local network creation
    driver: ${NETWORK_DRIVER:-bridge}
