version: '3.8'

services:
  fogis-api-client:
    build:
      context: .
      dockerfile: Dockerfile.dev
    container_name: fogis-api-client-dev
    networks:
      - fogis-network
    ports:
      - "8080:8080"
    environment:
      - PYTHONUNBUFFERED=1
      - FLASK_ENV=development
      - FLASK_DEBUG=1
      - TZ=Europe/Stockholm
      - PIP_EXTRA_INDEX_URL=https://pypi.org/simple
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/"]
      interval: 10s
      timeout: 5s
      retries: 3
      start_period: 10s
    restart: unless-stopped
    command: ["python", "fogis_api_gateway.py"]

  mock-fogis-server:
    build:
      context: .
      dockerfile: Dockerfile.mock
    container_name: mock-fogis-server
    networks:
      - fogis-network
    ports:
      - "5001:5001"
    environment:
      - PYTHONUNBUFFERED=1
      - FLASK_ENV=development
      - FLASK_DEBUG=1
      - MOCK_SERVER_PORT=5001
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:5001/health"]
      interval: 10s
      timeout: 5s
      retries: 3
      start_period: 10s
    restart: unless-stopped

  integration-tests:
    build:
      context: .
      dockerfile: Dockerfile.test
    container_name: fogis-api-client-tests
    networks:
      - fogis-network
    environment:
      - PYTHONUNBUFFERED=1
      - API_URL=http://fogis-api-client-dev:8080
      - MOCK_SERVER_URL=http://mock-fogis-server:5001
      - PYTHONDONTWRITEBYTECODE=1
    depends_on:
      - fogis-api-client
      - mock-fogis-server
    command: ["pytest", "integration_tests", "-v", "--log-cli-level=INFO"]

networks:
  fogis-network:
    driver: bridge
