name: Check Pre-commit Hooks

on:
  schedule:
    - cron: '0 0 * * 1'  # Run weekly on Mondays
  workflow_dispatch:  # Allow manual triggering

jobs:
  check-hooks:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
      
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install google-generativeai python-dotenv pyyaml
      
      - name: Check if hooks need updating
        env:
          GOOGLE_GEMINI_API_KEY: ${{ secrets.GOOGLE_GEMINI_API_KEY }}
        run: |
          python scripts/check_precommit_hooks.py
          if [ $? -eq 1 ]; then
            echo "Hooks need updating. Creating PR..."
            # Create a branch
            git config --global user.name "GitHub Actions"
            git config --global user.email "actions@github.com"
            git checkout -b auto-update-precommit-hooks
            
            # Generate new hooks
            python scripts/dynamic_precommit_generator.py --non-interactive
            
            # Commit and push
            git add .pre-commit-config.yaml .pre-commit-hooks/
            git commit -m "Auto-update pre-commit hooks"
            git push -u origin auto-update-precommit-hooks
            
            # Create PR
            gh pr create --title "Auto-update pre-commit hooks" \
                         --body "This PR was automatically created by the Check Pre-commit Hooks workflow. It updates the pre-commit hooks based on recent changes to the codebase." \
                         --base develop
          else
            echo "Hooks are up to date."
          fi
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
