name: CI Status Tracker

# Temporarily disabled due to missing external reusable workflow
# Re-enable when PitchConnect/.github repository has the required workflow
on:
  workflow_dispatch:  # Manual trigger only
  # workflow_run:
  #   workflows: ["*"]
  #   types: [completed]

jobs:
  disabled_notice:
    runs-on: ubuntu-latest
    if: github.event_name == 'workflow_dispatch'
    steps:
      - name: Notice
        run: |
          echo "CI Status Tracker is temporarily disabled"
          echo "Reason: Missing external reusable workflow PitchConnect/.github/.github/workflows/ci-failure-tracker.yml"
          echo "This workflow will be re-enabled when the external dependency is available"
