name: Docker Build and Test

on:
  push:
    branches: [ "main", "feature/*" ]
  pull_request:
    branches: [ "main" ]
  release:
    types: [published]

jobs:
  docker-build-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build development Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./Dockerfile.dev
          push: false
          load: true
          tags: fogis-api-client:dev
          cache-from: type=gha
          cache-to: type=gha,mode=max

      - name: Create test environment
        run: |
          mkdir -p data logs test-results
          echo "FOGIS_USERNAME=test_user" > .env.dev
          echo "FOGIS_PASSWORD=test_password" >> .env.dev
          echo "FLASK_ENV=development" >> .env.dev
          echo "FLASK_DEBUG=1" >> .env.dev

          # Create the Docker network
          docker network create fogis-network || true

      - name: Run unit tests
        run: |
          # Run unit tests only (no integration tests)
          docker run --rm fogis-api-client:dev sh -c "cd /app && python -m pytest tests/ -v"

      - name: Skip integration tests (for now)
        run: |
          echo "Skipping integration tests as they require a running server"
          echo "Integration tests will be run in a separate workflow"

  docker-build-prod:
    runs-on: ubuntu-latest
    needs: docker-build-test
    if: github.event_name == 'release'  # Only run on release events
    steps:
      - uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Extract metadata for Docker
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ghcr.io/${{ github.repository_owner }}/fogis-api-client
          tags: |
            type=semver,pattern={{version}}
            type=semver,pattern={{major}}.{{minor}}
            type=ref,event=branch
            type=sha

      - name: Build and push production Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          cache-from: type=gha
          cache-to: type=gha,mode=max
