name: Label Creator

on:
  workflow_dispatch:

jobs:
  create-labels:
    runs-on: ubuntu-latest
    permissions:
      issues: write
    steps:
      - name: Create standard labels
        run: |
          # Define labels as JSON array
          LABELS='[
            {"name":"triage","color":"fbca04","description":"Needs triage by maintainers"},
            {"name":"in-progress","color":"0052cc","description":"Issue is being worked on in a draft PR"},
            {"name":"review-ready","color":"5319e7","description":"Work is complete and ready for review"},
            {"name":"merged-to-develop","color":"0e8a16","description":"Implementation has been merged to develop"},
            {"name":"released","color":"1d76db","description":"Feature has been released to production"}
          ]'
          
          # Create each label
          echo "$LABELS" | jq -c '.[]' | while read -r label; do
            NAME=$(echo "$label" | jq -r '.name')
            COLOR=$(echo "$label" | jq -r '.color')
            DESC=$(echo "$label" | jq -r '.description')
            
            echo "Processing label: $NAME"
            
            # Check if label exists
            STATUS=$(curl -s -o /dev/null -w "%{http_code}" \
              -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" \
              -H "Accept: application/vnd.github.v3+json" \
              "https://api.github.com/repos/${{ github.repository }}/labels/$NAME")
            
            # Create label if it doesn't exist
            if [[ $STATUS -eq 404 ]]; then
              curl -X POST \
                -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" \
                -H "Accept: application/vnd.github.v3+json" \
                "https://api.github.com/repos/${{ github.repository }}/labels" \
                -d "{\"name\":\"$NAME\",\"color\":\"$COLOR\",\"description\":\"$DESC\"}"
              echo "Created label $NAME"
            else
              echo "Label $NAME already exists"
            fi
          done
