name: Publish Python Package

on:
  release:
    types: [created]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install build twine
    - name: Build and publish
      env:
        TWINE_PASSWORD: ${{ secrets.PYPI_API_TOKEN }}
        TWINE_USERNAME: __token__
      run: |
        python -m build
        echo "Built package successfully"
        ls -la dist/
        echo "Uploading to PyPI with verbose output"
        twine check dist/*
        twine upload --skip-existing --verbose dist/*
