name: Publish Python Package

on:
  release:
    types: [created]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
      with:
        ref: main
        fetch-depth: 0
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install build twine
    - name: Debug setup.py
      run: |
        echo "Current setup.py content:"
        cat setup.py
        grep -n "version" setup.py
    - name: Modify setup.py version
      run: |
        # Extract version from release tag
        VERSION=${GITHUB_REF#refs/tags/v}
        echo "Extracted version: $VERSION"
        # Update version in setup.py
        sed -i "s/version=\".*\"/version=\"$VERSION\"/" setup.py
        echo "Updated setup.py:"
        cat setup.py | grep version
    - name: Build package
      run: python -m build
    - name: Build and publish
      uses: pypa/gh-action-pypi-publish@release/v1
      with:
        password: ${{ secrets.PYPI_API_TOKEN }}
        verbose: true
