name: Test

on:
  push:
    branches: [ "main", "feature/*" ] # Trigger on pushes to main and feature branches
  pull_request:
    branches: [ "main" ] # Trigger on pull requests to main

jobs:
  build:

    runs-on: ubuntu-latest # Use the latest Ubuntu runner

    steps:
    - uses: actions/checkout@v4 # Checkout the code

    - name: Set up Python 3.9 # Replace with your Python version
      uses: actions/setup-python@v5
      with:
        python-version: "3.9"

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install --upgrade -e .[dev]

    - name: Lint with flake8
      run: |
        # stop the build if there are Python syntax errors or undefined names
        flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
        # exit-zero treats all errors as warnings. The GitHub editor is 127 chars wide
        flake8 . --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics

    - name: Test with pytest
      run: |
        pytest tests/